"""update table max length

Revision ID: 87cc8010568e
Revises: c24d27d71cc9
Create Date: 2024-02-05 12:42:57.926629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87cc8010568e'
down_revision: Union[str, None] = 'c24d27d71cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_ja_0900_as_cs', length=255),
               type_=sa.String(length=32),
               nullable=True)
    op.alter_column('patients', 'age',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_ja_0900_as_cs', length=255),
               type_=sa.String(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'title',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(collation='utf8mb4_ja_0900_as_cs', length=255),
               nullable=False)
    op.alter_column('patients', 'age',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('patients', 'name',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(collation='utf8mb4_ja_0900_as_cs', length=255),
               nullable=False)
    # ### end Alembic commands ###
