version: '3.9'

services:
  web:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8000"
    depends_on:
      - app

  app:
    build: ./python
    container_name: fastapi
    volumes:
      - ../src:/src
    expose:
      - 8001
    environment:
      WATCHFILES_FORCE_POLLING: true
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  db:
    build: ./mysql
    container_name: mysql
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-store:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  # minio:
  #   build: ./minio
  #   container_name: minio
  #   environment:
  #     - MINIO_ROOT_USER=rootroot
  #     - MINIO_ROOT_PASSWORD=secretsecret
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   command: server --console-address ":9001" /data
  #   volumes:
  #     - ./minio/data:/data

  # mailhog:
  #   container_name: mailhog
  #   build: ./mailhog
  #   ports:
  #     - 8025:8025
  #   environment:
  #     MH_STORAGE: maildir
  #     MH_MAILDIR_PATH: /tmp
  #   volumes:
  #     # メールデータ
  #     - ./mailhog/maildir:/tmp

volumes:
  db-store:
