# version: 1
# disable_existing_loggers: false
# formatters:
#   default:
#     format: 'LOGGER %(asctime)s - %(name)s - %(levelname)s - %(message)s'
#     datefmt: '%Y-%m-%d %H:%M:%S'
# handlers:
#   # console:
#   #   class: logging.StreamHandler
#   #   formatter: default
#   file_handler:
#     level: 'INFO'
#     class: 'logging.handlers.WatchedFileHandler'
#     formatter: default
#     filename: '/tmp/edgar_errors.log'
#     mode: 'a'
#     encoding: 'utf-8'
# loggers:
#   uvicorn:
#     handlers:
#     # - console
#     - file_handler
#     level: INFO
# root:
#   level: 'DEBUG'
#   handlers:
#     - 'file_handler'


version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "LOGGER: %(asctime)s - %(levelname)s - %(message)s"
handlers:
  file_handler:
    # class: logging.handlers.RotatingFileHandler
    # filename: "/logs/app.log"
    # formatter: simple
    # maxBytes: 10485760  # 10MB
    # backupCount: 20
    # encoding: "utf-8"
    # level: INFO
    class: logging.handlers.TimedRotatingFileHandler
    filename: "logs/app.log"
    formatter: simple
    when: midnight
    backupCount: 30
    encoding: "utf-8"
    level: INFO
loggers:
  uvicorn:
    level: INFO
    handlers: [file_handler]
  uvicorn.error:
    # level: ERROR
    level: INFO
    handlers: [file_handler]
  uvicorn.access:
    level: INFO
    handlers: [file_handler]
  sqlalchemy.engine.Engine:
    level: INFO
    handlers: [file_handler]
  app:
    handlers:
      - file_handler
    level: INFO
root:
  handlers:
    - file_handler
  level: DEBUG

